[phases.setup]
packages = ["chromium", "fonts-liberation", "libnss3", "libatk1.0-0", "libx11-xcb1", "libxcomposite1", "libxdamage1", "libxrandr2", "libgbm1", "libxss1", "libxtst6", "xdg-utils"]

[services]
  type = "web"
  command = "node index.js"
  port = 3000