services:
  - type: web
    name: whatsapp-service
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
    plan: free
